

```{r}
#| label: load-pkgs
#| message: false

suppressWarnings(library(tidyverse))
library(knitr)
library(lubridate)

```

## Dataset Setup
```{r, warning=FALSE}
# set working directory
setwd("D:/Data scienc Class Fall 2023/Data Mining in R class/Final Project/project-final-The-Null-Wranglers")
# read in data
dew_data <- read.csv("data/DEW Rates.csv")
summary(dew_data)
```
Data Cleaning
```{r}
# the total student count is currently a char - convert to an int
# remove commas then convert
dew_data$Total.Student.Count <- as.integer(gsub(",", "", dew_data$Total.Student.Count))
```

```{r}
# remove courses that have a incomplete that is greater than 50%
dew_data <- dew_data %>% filter(Per.Ungraded..Incomplete < 50)
```

```{r}
# Remove winter semester
dew_data <- dew_data %>% 
  filter(TERM_LD != "Winter 2020", TERM_LD != "Winter 2018", TERM_LD != "Winter 2019")
```

```{r}
# remove courses that have less than 5 students
dew_data <- dew_data %>% 
  filter(Total.Student.Count > 5)
```

```{r}
# remove all graduate level courses as we will only consider undergraduate course 
dew_data <- dew_data %>% 
  filter(Course.Level != "Graduate")
```

```{r}
# remove summer courses
dew_data <- dew_data %>% filter(TERM_LD != "Summer 2021", TERM_LD != "Summer 2020", TERM_LD != "Summer 2019")
                              
```

```{r}
# remove courses that are independent study/directed research style courses
dew_data <- dew_data %>% filter(Course.Description != "Internship",
                                Course.Description != "Directed Research",
                                Course.Description != "Independent Study",
                                Course.Description != "Senior Capstone",
                                Course.Description != "Honors Thesis",
                                Course.Description != "Special Topics",
                                Course.Description != "Practicum",
                                Course.Description != "Honors Independent Study", 
                                Course.Description != "Honors Colloquium",
                                Course.Description != "Senior Mentoring Workshop", 
                                Course.Description != "Preceptorship",
                                Course.Description != "Honors Preceptorship",
                                Course.Description != "Honors Directed Research")

```


```{r}
# inspect data
summary(dew_data)
```
Should we remove some of these columns? 

## Plots
```{r}
# total number of courses per semester?
dew_data %>% 
  group_by(TERM_LD) %>% 
  ggplot(aes( x = TERM_LD,
              fill = TERM_LD))+
  geom_bar(position = "dodge")
```

```{r}
# courses by level
dew_data %>% 
  group_by(TERM_LD, Course.Level) %>% 
  ggplot(aes( x = TERM_LD,
              fill = Course.Level))+
  geom_bar(position = "dodge")
```
We need to explain why there is so many more upper division courses, and how are lower & upper division courses are defined

```{r}
#1 plot of enrollment grouped by division for each semester - Rohit
```


```{r}
#2 mean and median of each semester - Rohit

```


```{r}
#3 mean enrollment for course level by semester - Anjani

```

```{r fig.height=16, fig.width=12}
#4 facet wrap of colleges of upper and lower per semester by enrollment - Kristi
# courses by sections - some classes are offered more than once per semester could help explain the above results in course level
dew_data %>% 
  group_by(TERM_LD, Course.Level, College) %>% 
  summarise(total_enrolled = sum(Total.Student.Count)) %>% 
  ggplot(aes( x = TERM_LD,
              y = total_enrolled,
              fill = Course.Level))+
  geom_col(position = "dodge")+
  facet_wrap(~College, ncol=2)+
  labs(title = "Comparisons of Student Enrollment",
                                    x = "Semester",
                                    y = "Total Enrollment")
```

```{r}
#5 facet wrap of colleges of mean enrollment per semester <- Utkarsha

```

```{r}
#6 facet wrap of departments in top enrollment college of upper and lower per semester <- Dong

library(readr)
library(dplyr)

# Filter THE top 1 enrollment college
top_college <- dew_data %>%
  group_by(College) %>%
  summarise(total_enrollment = sum(Total.Student.Count)) %>%
  top_n(1) %>%
  pull(College)

# Filter data to include only the top college, the College of Science
top_college_data <- dew_data %>%
  filter(College %in% top_college)

#Create Facet Wrap 
ggplot(top_college_data, aes(x = TERM_LD, y = Total.Student.Count, fill = Course.Level)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~ Department) +
  theme_minimal() +
  labs(title = "Enrollment by Department", 
       x = "Semester", 
       y = "Enrollment Numbers") +
  scale_fill_brewer(palette = "Set1")+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

# The previous plot is hard to read due to too many departments' info displayed, thus I selected the 3 departments with top and least enrollment and tried again
# The top 3 group
high_enrollment_departments <- dew_data %>%
  group_by(Department) %>%
  summarize(avg_enrollment = mean(Total.Student.Count), .groups = "drop") %>%
  arrange(desc(avg_enrollment)) %>%
  slice_max(order_by = avg_enrollment, n = 3) %>%
  pull(Department)

# The bottom 3 group
low_enrollment_departments <- dew_data %>%
  group_by(Department) %>%
  summarize(avg_enrollment = mean(Total.Student.Count), .groups = "drop") %>%
  arrange(avg_enrollment) %>%
  slice_min(order_by = avg_enrollment, n = 3) %>%
  pull(Department)

# Plot for departments with higher enrollments
high_enrollment_plot <- ggplot(dew_data %>% filter(Department %in% high_enrollment_departments), 
                               aes(x = TERM_LD, y = Total.Student.Count, fill = Course.Level)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~ Department, scales = "free_y") +
  theme_minimal() +
  labs(title = "Top 3 Departments for Enrollment (College of Science)", 
       x = "Semester", 
       y = "Enrollment Numbers") +
  scale_fill_brewer(palette = "Set1") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

# Print or save the high_enrollment_plot
print(high_enrollment_plot)

# Plot for departments with lower enrollments
low_enrollment_plot <- ggplot(dew_data %>% filter(Department %in% low_enrollment_departments), 
                               aes(x = TERM_LD, y = Total.Student.Count, fill = Course.Level)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~ Department, scales = "free_y") +
  theme_minimal() +
  labs(title = "Bottom 3 Departments for Enrollment (College of Science)", 
       x = "Semester", 
       y = "Enrollment Numbers") +
  scale_fill_brewer(palette = "Set1") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

# Print or save the high_enrollment_plot
print(low_enrollment_plot)
```

